### ISSUE TITLE
사전 경로 미수정

### ISSUE THREAD

**Issue by lmh30003** [openkoreantext/open-korean-text#8]
안녕하세요, OpenKoreanText를 사용하다가 미수정된 것 같은 코드를 발견하여 글 올립니다.(github을 잘 안써봐서 여기 쓰는게 맞나 잘 모르겠네요)
scala/org/openkoreantext/processor/tools/DeduplicateAndSortDictionaries.scala 파일의 61번째 줄에
`val outputFolder = "src/main/resources/com/twitter/penguin/korean/util/"`
로 되어 있습니다. 옮겨오면서 누락된 것 같은데, 수정하는 것이 맞는 것 같습니다.

감사합니다

**Comment by lmh30003** [comment]
tools내 다른 파일들도 같은 문제가 있네요. 모두 기존의 twitter경로를 쓰고 있습니다

**Comment by openkoreantext** [comment]
Thanks for reporting and fixing the issue!
